const maps = [
    [
        "WWWWWWWWWWWWWWWWWWWWW",
        "W   W     W     W W W",
        "W W W WWW WWWWW W W W",
        "W W W   W     W W   W",
        "W WWWWWWW W WWW W W W",
        "W         W     W W W",
        "W WWW WWWWW WWWWW W W",
        "W W   W   W W     W W",
        "W WWWWW W W W WWW W F",
        "S     W W W W W W WWW",
        "WWWWW W W W W W W W W",
        "W     W W W   W W W W",
        "W WWWWWWW WWWWW W W W",
        "W       W       W   W",
        "WWWWWWWWWWWWWWWWWWWWW",
    ],
    [
        "WWWWWWWWWWWWWWWWWWWWW",
        "S   W WWW W         W",
        "WWW W     W WWWWWW WW",
        "W   WWWWW    W     WW",
        "W WWW   WWWW WW WWWWW",
        "W  WW W W    WW   W W",
        "WW WW W W WWWWW W W W",
        "WW WW W W   W W W W W",
        "WW    W WWW W W W   W",
        "WW WWWW       W WWW W",
        "WW WWWWWWWWWW W W   W",
        "W           W W W WWW",
        "W WWWWWWWWW W W W W F",
        "W         W W   W   W",
        "WWWWWWWWWWWWWWWWWWWWW"
    ],
    [
        "WWWWWWWWWWWWWWWWWWWWW",
        "W     W    WWWW     F",
        "W WWW WWWW WWWW WWWWW",
        "W WWW W       W     W",
        "S   W WW WWWW WWWWW W",
        "WWW W    WWWW W W W W",
        "W W WWWW WW   W W W W",
        "W   W    WW W   W W W",
        "W WWW WWWWWWW WWW W W",
        "W WW      WW   WW   W",
        "W WW WWWW WWWWWW  WWW",
        "W       W WW    W   W",
        "W WWWWW W    WW WWW W",
        "W       W WWWWW     W",
        "WWWWWWWWWWWWWWWWWWWWW"
    ],
    [
        "WWWWWWWWWWSWWWWWWWWWW",
        "W     W       W     W",
        "W WWW W WWWWW   W W W",
        "W W   W W   WWWWW W W",
        "W W WW  W W WWW   W W",
        "W W    WW W W   WWW W",
        "W WWWW WW W   WWWWW W",
        "W   WW WW WWWW    W W",
        "WW WW   W  WWW WW W W",
        "W  WWWW   WWWW WW W W",
        "W WW WWWW      WW W W",
        "W     W WWWWWW W  W W",
        "W W WWW    WWW W WW W",
        "W W     WW  W  W    W",
        "WWWWWWWWWWFWWWWWWWWWW"
    ],
    [
        "WWWWWWWWWWWWWWWWSWWWW",
        "W   W W       WW    W",
        "W W   W W WWWWWWW W W",
        "W WWW W W WW   WW W W",
        "W W     W    W W  W W",
        "W   WWWWWWWWWW   WW W",
        "W W    WW      WWW  W",
        "W WWWW WW W WWWW   WW",
        "W      W  W    W WWWW",
        "WWWW W WW W W WW WWWW",
        "W WW WWW  W W WW    W",
        "W      W WWWW  WWW WW",
        "W WWWW W   WWW W    W",
        "W W    WWW  W    WW W",
        "WWWFWWWWWWWWWWWWWWWWW"
    ],
    [
        "WWWWWSWWWWWWWWWWWWWWW",
        "W   W W   W WWW     W",
        "W W W W W W   WWWWW W",
        "W W     W W W   W   W",
        "W WWWWWWW W WWW W W W",
        "W      WW W W   W W W",
        "WW WWW WW W W W W W W",
        "WW W        W W   W W",
        "W  W WWWWWWWWWWWWWW W",
        "WWWW W  WW       WW W",
        "W    W WWW WWWWW W  W",
        "W WWWW W   W   W W WW",
        "W   WW W WWW W W W WW",
        "W W    W     W W    W",
        "WWWWWWWWWWWWWWFWWWWWW"
    ]
]